// Set empty variable longest
// For all elements in the array
// If the length of current element in array is greater than previous element
	// Set variable equal to that element
// Return variable 

function longest(arr) {
  var longest = 0;
  for (i = 1; i < arr.length; i++){
	if (arr[i].length > arr[i-1].length) {
	  longest = arr[i];
	}
  }
  return longest;
}

// Set tracking variable to default to false
// For each key in first object and each key in second object
	// If the first object's key and second object's key are the same and the values for the keys are the same too
		// Set the tracker's value to true
// Return the value of the tracker (true or false)

function similar(obj1, obj2) {
  tracker = false;
  for (key in obj1){
 	for(key2 in obj2){
 	  if (key == key2 && obj1[key] == obj2[key2]) {
 	    tracker = true;
 	  }
 	}
  }
  return tracker;
}

// Initialize empty array to hold array of words
// Set a string equal to all the letters of the alphabet
// Iterate through each element of the output array and adding the user inputted number of elements to the array
	// Initialize empty string for each element
	// For 1 to a random number generated by random_num for the length of the word,
		// Concatenate a random letter chosen from the alphabet string to the word
	// Set the element in the output array equal to the generated word
// Return the array filled with words

function generate_random(num) {
  var new_string = [];
  var string = "abcdefghijklmnopqrstuvwxyz";

  for(k = 0; k < num; k++) {
  	var word = '';
  	
  	for (i = 1; i < random_num(); i++) {
		word += string.charAt(Math.floor(Math.random() * string.length));
  	}
  	new_string[k] = word;
  }
  return new_string;
}  

// Set variable equal to 0
// Set the variable to a random number between 1 and 10
// Return the random number

function random_num (){
  var random = 0;
  random = Math.floor(Math.random() * (10) + 1);
  return random;
}


// Driver code

console.log(longest(["long phrase","longest phrase","longer phrase"]));
console.log(longest(["cat", "fish", "snake", "bat"]));

console.log(similar({name: "Steven", age: 54}, {name: "Tamir", age: 54}));
console.log(similar({shade: "red", size: 10, isCool: true}, {color: "red", size: 11, isCool: false}));

/* For some reason, the following code causes the loop to run forever instead of just 10 times, so I had to manually loop it 10 times.

for (i = 0; i < 10; i++) {
  console.log(longest(generate_random(3)));
  
}*/

console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));
console.log(longest(generate_random(3)));

